BUILD_DIR = build

# FPGA settings
FPGA_PART = xc7z010clg400-1
FPGA_TOP = led

# Files for synthesis
SYN_FILES = led.v

# XDC files
XDC_FILES = pinout.xdc

# IP
# IP_TCL_FILES += ip/eth_xcvr_gt.tcl

# Configuration
CONFIG_TCL_FILES = config.tcl

include ../scripts/vivado.mk

