# [MyProject]

default:
	mkdir build -p && cd build && qmake .. && make -j8

run:
	./build/release/qtdemo.exe

clean:
	@rm build -rf 2> /dev/null || true

fullclean:
	@rm build -rf 2> /dev/null || true

