#!/usr/bin/env python
  # -*- coding: UTF-8 -*-
  
import os, sys
from kconfiglib import Kconfig
from menuconfig import menuconfig

def mconf_set_env():
    """
    Set Kconfig Env
    """
    os.environ["MENUCONFIG_STYLE"] = "default selection=fg:white,bg:blue"
    os.environ["KCONFIG_CONFIG"] = os.path.join(".config")
    os.environ["KCONFIG_CONFIG_HEADER"] = "# Generated by My Kconfig Demo"
    os.environ["KCONFIG_AUTOHEADER"] = os.path.join("config.h")
    os.environ["CONFIG_"] = ""

def mconfig(argv):
    mconf_set_env()
    kconf = Kconfig(filename="./config.in")
    menuconfig(kconf)
    kconf.write_autoconf()

if __name__ == "__main__":
    mconfig(sys.argv)
